### ISSUE TITLE
AttributeError: 'int' object has no attribute 'cycle'

### ISSUE THREAD

**Issue by wyq87** [rostaresearch/unbinding#1]
when I use command `main.py --step step1 -l PI -t 0`,  it reported the error: 
```
Traceback (most recent call last):
  File "/gpfs/home/fxia/software/unbinding-main/main.py", line 40, in <module>
    c = rp.Cycle(Unb.cycle)
  File "/gpfs/home/fxia/software/unbinding-main/src/read_pdb.py", line 40, in __init__
    self.number = unbinding.cycle
AttributeError: 'int' object has no attribute 'cycle'
```
I don't know what `-t` means. In the file REMDME.md, for `-t` argument,the default is "last trajectory",but its type is int,I am confused.
Moreover,Could you please provide a example to understand easlier the whole process?

**Comment by bertadenes** [comment]
`-t` declares what trajectory has to be processed to determine the colvars, `-t 0` is looking for a dcd in the folder `traj_0`
The issue came from some errors in the ill maintained step1 section, but in fact you do not need that in a production setting, please try without that flag.
Fixed in #f24991cf0ff15c685986a1d1921565b8c80ba9ff
I hope to get around providing an example.
